### ISSUE TITLE
Trying to delete my files

### ISSUE THREAD

**Issue by trajano** [jaymoulin/docker-google-music-uploader#9]
I mounted my library folder in read only mode since i didn't expect any changes to be done by the tool  however I saw the following in my logs

```
misc_googlemusic.1.zgmtgutcw7y4@worker2    | Traceback (most recent call last):
misc_googlemusic.1.zgmtgutcw7y4@worker2    |   File "/usr/local/bin/google-music-upload", line 11, in <module>
misc_googlemusic.1.zgmtgutcw7y4@worker2    |     sys.exit(main())
misc_googlemusic.1.zgmtgutcw7y4@worker2    |   File "/usr/local/lib/python3.6/site-packages/google_music_manager_uploader/uploader_daemon.py", line 75, in main
misc_googlemusic.1.zgmtgutcw7y4@worker2    |     upload(args.directory, args.oauth, args.remove, args.uploader_id)
misc_googlemusic.1.zgmtgutcw7y4@worker2    |   File "/usr/local/lib/python3.6/site-packages/google_music_manager_uploader/uploader_daemon.py", line 54, in upload
misc_googlemusic.1.zgmtgutcw7y4@worker2    |     os.remove(file_path)
misc_googlemusic.1.zgmtgutcw7y4@worker2    | OSError: [Errno 5] I/O error: '/media/library/DE/Alphaville/First Harvest 1984-92/14 - Alphaville - Forever Young.mp3'

```
Why is it trying to do a `os.remove(file_path)`?

**Comment by trajano** [comment]
I also tried setting

```
    environment:
    - REMOVE=false
```

and

    - REMOVE=0
